name: book_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  flutter_svg: ^1.0.3
  fluttertoast: ^8.2.0
  syncfusion_flutter_pdfviewer: ^20.3.0
  lottie: ^2.2.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.1
  google_sign_in: ^5.4.1
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.4
  image_picker: ^1.0.6
  file_picker: ^5.3.0
  uuid: ^3.0.7
  sqflite: ^2.0.0+4  # SQLite database
  path: ^1.8.0  # Path package for SQLite
  shared_preferences: ^2.0.8 # For shared preferences
  flutter_rating_bar: ^4.0.1 # Rating functionality

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/
    - Assets/Icons/
    - Assets/Animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins-SemiBold.ttf
          weight: 600
