// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1AUNG5p2GaC2CEV3D-ZbJTFV7UP8Nc24',
    appId: '1:891450092416:web:bbbd8f54f7884fa40caf65',
    messagingSenderId: '891450092416',
    projectId: 'book-app-store-47891',
    authDomain: 'book-app-store-47891.firebaseapp.com',
    storageBucket: 'book-app-store-47891.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEi0xKgZI67XMZW_P4b_QIUR0NnnFy7L0',
    appId: '1:891450092416:android:27ca477ab43e8fc50caf65',
    messagingSenderId: '891450092416',
    projectId: 'book-app-store-47891',
    storageBucket: 'book-app-store-47891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJWzWNvrmDnx08ZdGdKkxDS9iQ_6sgzY',
    appId: '1:891450092416:ios:6da8e4b0828286e40caf65',
    messagingSenderId: '891450092416',
    projectId: 'book-app-store-47891',
    storageBucket: 'book-app-store-47891.appspot.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyJWzWNvrmDnx08ZdGdKkxDS9iQ_6sgzY',
    appId: '1:891450092416:ios:6da8e4b0828286e40caf65',
    messagingSenderId: '891450092416',
    projectId: 'book-app-store-47891',
    storageBucket: 'book-app-store-47891.appspot.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1AUNG5p2GaC2CEV3D-ZbJTFV7UP8Nc24',
    appId: '1:891450092416:web:e4a3f4d7570f7d660caf65',
    messagingSenderId: '891450092416',
    projectId: 'book-app-store-47891',
    authDomain: 'book-app-store-47891.firebaseapp.com',
    storageBucket: 'book-app-store-47891.appspot.com',
  );
}
